metadata.rb
recipes/filter-client-authorization.rb
templates/default/openstack-authorization.cfg.xml.erb

This is the default location for the client authz filter.

Renamed client authz template to openstack-authz

---

metadata.rb
recipes/install_debian.rb
recipes/install_rhel.rb

Repose broke up their packages a bit based on some internal criteria.  This resolves that.

Add repose-extensions-filter-bundle

---

README.md

The current `README` doesn't match our actual testing infrastructure.

Make 'supported platforms' match kitchen.yml

---

attributes/default.rb
metadata.rb
recipes/filter-client-auth.rb
templates/default/client-auth-n.cfg.xml.erb

The Repose documentation lists a `client-auth` filter option for allowing administrator tokens to hit resources owned by other tenants without validation: `service-admin-roles`
https://repose.atlassian.net/wiki/display/REPOSE/Client+Authentication+filter#ClientAuthenticationfilter-Tenantedmode
This option is missing from the recipe, and we'd like to use it for Cloud DNS's designate environment.
This change was validated locally with the Cloud DNS team's virtualbox-based test kitchen setup.

Adding support for the service-admin-roles element in the client-auth filter

---

README.md
attributes/default.rb
metadata.rb
recipes/filter-rate-limiting.rb
templates/default/rate-limiting.cfg.xml.erb

https://repose.atlassian.net/wiki/display/REPOSE/Rate+Limiting+filter#RateLimitingfilter-Globalratelimits
This allows you to optionally turn on Global Rate Limits very similarly
to how it is done for Rate Limit Groups elsewhere in this cookbook,
albeit slightly different due to how Global Rate Limits are implemented
in Repose.
This requires Repose >= 6.1.0.3, but if youre not there yet you have
bigger problems. :trollface:

Add support for Global Rate Limits

---

Berksfile
recipes/default.rb
recipes/install.rb
test/unit/spec/default_spec.rb
test/unit/spec/install_debian_spec.rb
test/unit/spec/install_rhel_spec.rb
test/unit/spec/install_spec.rb
test/unit/spec/spec_helper.rb

Add basic unit tests for default and install recipes.  Minor cleanup associated with the unit tests.
We are depending on this cookbook downstream and it would be good to add unit tests in a more current chefspec model.
Add test/unit/spec directory with some basic tests and a spec_helper.rb file.  Currently achieved 100% coverage on default.rb, install.rb, install_rhel.rb and install_debian.rb.
To test with ChefDK installed run $ chef exec rspec test/unit
Continue to add more unit tests.  Add documentation on adding/running tests.

Initial chefspec unit tests and minor cleanup

---

.kitchen.yml
README.md
attributes/default.rb
recipes/service-response-messaging.rb
test/unit/spec/service-response-messaging_spec.rb

This PR implements some minor cleanup in the .kitchen.yml file.  Followed up by verifying that a kitchen converge and kitchen verify runs on every flavor listed.
Note: This does not include the new filter-ip-user coming in next PR.
Fixed some issues with the naming of the response_messaging attribute which needed to use underscores instead of dashes.

Clean up .kitchen.yml, fix issues for service-response-messaging

---

CHANGELOG.txt
metadata.rb
templates/default/system-model.cfg.xml.erb

Bumping to 3.3.3 after a few PRs with cleanup and added recipes.  Fixing a minor bug where declaring multiple peers via attributes (and not search) failed because of the .sort in system-model template.

Minor bug fix and version bump.

---

attributes/default.rb
recipes/default.rb
recipes/filter-api-validator.rb
templates/default/container.cfg.xml.erb
templates/default/ip-user.cfg.xml.erb
templates/default/keystone-v2.cfg.xml.erb
templates/default/validator.cfg.xml.erb

In working towards deploying Repose 7.x in Rackspace Metrics environment I have found some small bugs and small formatting nits.  Several small fixes below.
attributes/default.rb - add some default values for services cluster_id to match up
recipes/default.rb - add services to server_cluster_map to match others, add missing variables in container template resource
recipes/filter-api-validator.rb - add missing variables that need to be passed to template resource if they exist
templates/default/container.cfg.xml.erb - fix variable bug
templates/default/ip-user.cfg.xml.erb - fix incorrect variable naming
templates/default/keystone-v2.cfg.xml.erb - fix formatting so that output doesn't show up with blank lines/spaces
templates/default/validator.cfg.xml.erb - fix formatting so that blank …

cookbook nits and minor fixes.

---

attributes/default.rb
recipes/filter-api-validator.rb
recipes/filter-rate-limiting.rb
templates/default/rate-limiting.cfg.xml.erb
templates/default/validator.cfg.xml.erb

Add additional attributes for filter-api-validator recipe.  The API Validation filter has several variables we don't include - this finished optional attributes for the rate-limiting element.
Set the multi-role-match attribute of the validators element to be optional, it will be deprecated in the upcoming Repose v8.
Updated templates, recipes and default attributes.

continued 3.3.4 development

---

templates/default/rate-limiting.cfg.xml.erb

Because I am setting the value to nil, needed to specify to print if they didn't equal nil.
Forget the equal sign to actually interpolate the attributes when they are passed along.

More template fixes

---

CHANGELOG.txt
attributes/default.rb
templates/default/log4j2.xml.erb

Update configuration for default log in log4j2.xml.erb template.  The current version had a date string in the filename portion, but that doesn't work properly with the DefaultRolloverStrategy attribute.
Set the default version to 7.3.6.0 (was nil) as version 8.x.x.x has been released now and deprecates Java 7.
Switch to using a numeric value using %i, drop the date naming.  Change the default set to 5 logs of 1024MB each.
Update attributes with version.  Update CHANGELOG.
Tag as version 3.3.4 after PR is reviewed and merged.
http://stackoverflow.com/questions/13502722/log4j2-limiting-the-number-of-log-files
http://stackoverflow.com/questions/24551768/how-does-log4j2-defaultrolloverstrategys-max-attribute-really-work

Update log4j2 template to have better rotation by default

---

CHANGELOG.txt
attributes/default.rb
metadata.rb
templates/default/log4j2.xml.erb
templates/default/rate-limiting.cfg.xml.erb

Bump to version 3.3.5.  Fix a case error for the overLimit-429-responsecode attribute in the rate-limiting.cfg.xml template.  Update basic logging defaults to be less of a hog.
Updates in templates and to metadata.rb.
After review and merge, tag as 3.3.5.

version 3.3.5 - fix overLimit-429-responsecode bug

---

metadata.rb
templates/default/keystone-v2.cfg.xml.erb

The existing XML tags in the template are incorrect.  fixing.

fixing keystone-v2 whitelist xml tags.

---

attributes/default.rb

Previously enable_rax_roles was set to both true and false.  enable_api_coverage was set to true.  They are both optional to the API Validator filter, so they should be set to nil in the attributes/default.rb file.

Update enable_api_coverage and enable_rax_roles attributes

---

CHANGELOG.txt
metadata.rb
templates/default/dist-datastore.cfg.xml.erb

Fix allowed_hosts sorting bug in dist-datastore template.

should be .sort.each vs .each.sort

---

README.md

The example for `node['repose']['rate_limiting']['limit_groups']` in the README uses `uri-regex` and `http-methods` but the [template code](https://github.com/rackerlabs/cookbook-repose/blob/master/templates/default/rate-limiting.cfg.xml.erb#L31) actually uses `uri_regex` and `http_methods` so lets update the README (also whitespace cleanup).
resolves #79

update limit_groups README example to reflect actual names

---

.kitchen.docker.yml
.kitchen.yml

This should enable systemd to run in the CentOS7 container in Travis and pass tests.

fix for .kitchen.docker.yml to run Travis Centos7 tests

---

CHANGELOG.txt
metadata.rb
recipes/filter-client-auth.rb
recipes/filter-client-authorization.rb
recipes/filter-keystone-v2.rb

Fix permissions on client-auth, keystone-v2 and openstack-authorization files in /etc/repose.  Those files were 0644 and should at most be 0640.
After review, tag a version at 3.3.8.

fix mode on files which have credentials

---

attributes/default.rb
recipes/install_debian.rb

Changing the way we install repose-valve and dependent packages, because if the packages are installed one by one, repose 9.1 creeps in when we install repose-valve due to some inter-dependency.

Fix repose pkgs installation method

---

metadata.rb
templates/default/log4j2.xml.erb

Repose is logging out a line at info level for each request that basically only contains the unique request/transaction id. They look like this:
Trans-Id:462d1c98-21ee-4041-9117-d9563fb9e054 - 2022-01-18 16:00:14,753 34371166201 [qtp1966366279-481452] INFO  org.openrepose.powerfilter.PowerFilter.trace-id-logging - Tracing header: {"requestId":"462d1c98-21ee-4041-9117-d9563fb9e054","origin":null}
Without any other context, it's pretty useless, but they outnumber other logs by a couple hundred to one:
$ sudo cat /var/log/repose/current.1.log | grep 'trace-id-logging - Tracing header' | wc -l
823883
$ sudo cat /var/log/repose/current.1.log | grep -v 'trace-id-logging - Tracing header' | wc -l
3983
We can add a line to repose's log4j config to turn off these logs when we don't need them. …

Reduce repose request tracing logs

---

templates/default/add-header.cfg.xml.erb

While updating the repose for blueflood-chef, we found out that this condition is wrong. So reversed the condition as with new version rackspace link is not valid.

Update the add-header filter template

---

templates/default/container.cfg.xml.erb

While upgrading repose for blueflood-chef, we found out that some attributes of container deployment config are depricated after repose version 7.3.8. Attributes depricated are connection-timeout,  read-timeout and client-request-logging.
For connection-timeout and read-timeout, we found out that we can set these properties in http-pool-connection.cfg filter file present in [repose code](https://github.com/rackerlabs/repose/blob/master/repose-aggregator/artifacts/valve/src/config/filters/http-connection-pool.cfg.xml)
For read-timeout, we can set attribute http.socket-timeout as mentioned in its [schema](https://github.com/rackerlabs/repose/blob/f9a5ddcce0e2da4c1fcacd9f8f70d3dfb403c1bc/repose-aggregator/components/services/http-client-service/http-client-service-api/src/main/resources/META- …

Container config update for repose upgrade

---

metadata.rb

there have been two releases, 3.6.2, and 3.6.3 where the metadata.rb
file has not been updated. this leads to an inconsistency in the
Berksfile.lock when updating to either of these versions, as you have
3.6.x in the Berksfile, but a `berks update|install` will still write
the (older) version listed in metadata.rb into the Berksfile.lock

bump metadata version to 3.6.4

---

attributes/default.rb

apt `--force-yes` option is deprecated and has no effect to force install the packages. For repose upgrade/downgrade, packages need corresponding force install option.
Without fix, chef-client run logs:
```
==> default:     ================================================================================
==> default:     Error executing action `run` on resource 'bash[install repose packages]'
==> default:     ================================================================================
==> default:
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     Expected process to exit with [0], but received '1'
==> default:     ---- Begin output of "bash"  "/tmp/chef-script20240501-30886-1n54b6h" ----
==> default:     STDOUT: …
```

fix for --force-yes removal from apt install
